### ISSUE TITLE
Who tells who is and who is not a fascist?

### ISSUE THREAD

**Issue by galkowskit** [jamiebuilds/anti-fascist-mit-license#7]
Is it self-conscience thing or will someone monitor, IDK, Twitter behaviour and retract license agreement if a developer from an XYZ company is deemed fascist?

**Comment by AntifaPizza** [comment]
@galkowskit - Jamie should be in charge of deciding who is a facist. He is the creator of this license and it would be unwise if we didn't grant him absolute authority.

I suggest we start by compiling lists of suspected facists so we can dox them all and make sure they can't find employment and are ostracized from their local communities. We must be absolute with our authority here in order to forcible suppress anyone who opposes us.

Linked discussion: #4

**Comment by jamiebuilds** [comment]
I'm happy to leave it as anyone who is concerned about violating the license should avoid using my software.
